// Code generated by "stringer -type KeywordKind keyword.go"; DO NOT EDIT.

package dialect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Matched-0]
	_ = x[DML-1]
	_ = x[DDL-2]
	_ = x[DCL-3]
}

const _KeywordKind_name = "MatchedDMLDDLDCL"

var _KeywordKind_index = [...]uint8{0, 7, 10, 13, 16}

func (i KeywordKind) String() string {
	if i < 0 || i >= KeywordKind(len(_KeywordKind_index)-1) {
		return "KeywordKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeywordKind_name[_KeywordKind_index[i]:_KeywordKind_index[i+1]]
}
